# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#Importation des modules
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import QObject
#   QMessageBox n'était pas importer depuis QtWidgets et doit être forcer ainsi que filedialog
from PyQt5 import QtCore, QtGui, QtWidgets

#from classes import Personne
from classes2 import *

class Ui_Application(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.resize(1087, 627)
        Application.setSizeGripEnabled(True)
        self.tabMain = QtWidgets.QTabWidget(Application)
        self.tabMain.setGeometry(QtCore.QRect(30, 30, 991, 531))
        self.tabMain.setObjectName("tabMain")
        ### DEBUT DE LA TAB FILMS ####
        self.tabFilms = QtWidgets.QWidget()
        self.tabFilms.setObjectName("tabFilms")

        # Bouton précédent de la tab Films
        self.btnPrecedent_2 = QtWidgets.QPushButton(self.tabFilms)
        self.btnPrecedent_2.setGeometry(QtCore.QRect(50, 140, 31, 23))
        self.btnPrecedent_2.setObjectName("btnPrecedent_2")

        # Bouton Suivant de la tab Films
        self.btnSuivant_2 = QtWidgets.QPushButton(self.tabFilms)
        self.btnSuivant_2.setGeometry(QtCore.QRect(110, 140, 31, 23))
        self.btnSuivant_2.setObjectName("btnSuivant_2")

        ## Layout vertical contenant les boutons nouveaux et supprimer
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tabFilms)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 160, 112))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")

        # Bouton pour enregistrer une nouvelle entrée Film
        self.btnNouveau_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnNouveau_3.setObjectName("btnNouveau_3")
        self.verticalLayout_21.addWidget(self.btnNouveau_3)
        self.btnNouveau_3.clicked.connect(self.newFilm)

        # Bouton pour supprimer l'entré film sélectionné
        self.btnSupprimer_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnSupprimer_3.setObjectName("btnSupprimer_3")
        self.verticalLayout_21.addWidget(self.btnSupprimer_3)

        ## Layout vertical contenant les informations du films
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tabFilms)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(220, 20, 211, 171))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")

        # Lineedit Contenant le titre du film
        self.lineFilm_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.lineFilm_2.setObjectName("lineFilm_2")
        self.lineFilm_2.setText('Inscrire le titre du film')
        self.verticalLayout_22.addWidget(self.lineFilm_2)
        self.lineFilm_2 = film.nomFilm(self)

        # Lineedit avec la durée du film
        self.dureeFilm = QtWidgets.QTimeEdit(self.verticalLayoutWidget_4)
        self.dureeFilm.setObjectName("dureeFilm")
        self.verticalLayout_22.addWidget(self.dureeFilm)
        self.dureeFilm = film.catFilm(self)

        # TextEdit contenant une description du film
        self.textDescFilm_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self.textDescFilm_2.setObjectName("textDescFilm_2")
        self.textDescFilm_2.setText('Inscrire la synopsie du film')
        self.verticalLayout_22.addWidget(self.textDescFilm_2)
        self.textDescFilm_2 = film.descFilm(self)

        ## Grid layout contenant les checkbox des catégories de films
        self.label_2 = QtWidgets.QLabel(self.tabFilms)
        self.label_2.setGeometry(QtCore.QRect(520, 10, 111, 20))
        self.label_2.setObjectName("label_2")

        self.cbListCatFilm = ["Animation", "Fantaisie", "Science-Fiction", "Horreur", "Drame",
                             "Thriller", "Documentaire", "Comédie"]
        self.listCatFilm    = ['', '', '', '', '', '', '', '', ]

        for i, v in enumerate(self.cbListCatFilm):
            self.cbListCatFilm[i] = QtWidgets.QCheckBox(v)
            self.listCatFilm[i] = QtWidgets.QLabel()
            QtWidgets.QGridLayout(self.cbListCatFilm[i], i, 0)
            QtWidgets.QGridLayout.grid.addWidget(self.listCatFilm[i],    i, 1)


        self.tabMain.addTab(self.tabFilms, "")

        # Bouton de fermeture lancant un QMessageBox de confirmation
        self.btnFermer = QtWidgets.QPushButton(Application)
        self.btnFermer.setGeometry(QtCore.QRect(940, 570, 75, 23))
        self.btnFermer.setObjectName("btnFermer")
        self.btnFermer.clicked.connect(self.closeEvent)

        # Bouton de sauvegarde des données
        self.btnSauvegarder = QtWidgets.QPushButton(Application)
        self.btnSauvegarder.setGeometry(QtCore.QRect(540, 570, 158, 23))
        self.btnSauvegarder.setObjectName("btnSauvegarder")
        self.btnSauvegarder.clicked.connect(self.sauvegarder)

        # Bouton de chargement des données
        self.btnCharger = QtWidgets.QPushButton(Application)
        self.btnCharger.setGeometry(QtCore.QRect(700, 570, 158, 23))
        self.btnCharger.setObjectName("btnCharger")
        self.btnCharger.clicked.connect(self.charger)

        self.retranslateUi(Application)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Application)

 ### Enregistrement de l'entré et remise à zero des films ###
    def newFilm(self):
        self.Film._catFilm.setText("")
        for i, v in enumerate(self.listCheckBox):
            self.listLabel[i].setText("True" if v.checkState() else "False")


    # Fenêtre de confirmation de la fermeture de l'application
    def closeEvent(self):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Êtes-vous sure de quitter?")
        msgBox.setWindowTitle("Message de fermeture")
        msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        #   Choix du message de fermeture
        res = msgBox.exec_()
        if res == QMessageBox.Ok:
            sys.exit()
        if res == QMessageBox.Cancel:
            return True
        return False

 ### Sauvegarde à retravailler ###
    def sauvegarder(self):
        name = QtGui.QFileDialog.getSaveFileName(self, 'Save File')
        file = open(name,'w')
        text = self.textEdit.toPlainText()
        file.write(text)
        file.close()

 ### Chargement à retravailler ###
    def charger(self):
        name = QtGui.QFileDialog.getOpenFileName(self, 'Open File')
        file = open(name, "r")
        self.ListeDePersonnes = file.load(file)
        file.close()
        self.contactsUpdate()

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(_translate("Application", "Dialog"))


        self.btnPrecedent_2.setText(_translate("Application", "<"))
        self.btnSuivant_2.setText(_translate("Application", ">"))
        self.btnNouveau_3.setText(_translate("Application", "Nouveau"))
        self.btnSupprimer_3.setText(_translate("Application", "Supprimer"))
        self.label_2.setText(_translate("Application", "Catégories du film"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabFilms), _translate("Application", "Films"))
        self.btnFermer.setText(_translate("Application", "Fermer"))
        self.btnSauvegarder.setText(_translate("Application", "Sauvegarder"))
        self.btnCharger.setText(_translate("Application", "Charger"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Application = QtWidgets.QDialog()
    ui = Ui_Application()
    ui.setupUi(Application)
    Application.show()
    sys.exit(app.exec_())
