# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Acteurs.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Acteurs(object):
    def setupUi(self, Acteurs):
        Acteurs.setObjectName("Acteurs")
        Acteurs.resize(380, 269)
        self.btnCloseActeur = QtWidgets.QPushButton(Acteurs)
        self.btnCloseActeur.setGeometry(QtCore.QRect(250, 210, 75, 23))
        self.btnCloseActeur.setObjectName("btnCloseActeur")
        self.btnSaveActeur = QtWidgets.QPushButton(Acteurs)
        self.btnSaveActeur.setGeometry(QtCore.QRect(150, 210, 75, 23))
        self.btnSaveActeur.setObjectName("btnSaveActeur")
        self.btnPrecActeur = QtWidgets.QPushButton(Acteurs)
        self.btnPrecActeur.setGeometry(QtCore.QRect(50, 210, 31, 23))
        self.btnPrecActeur.setObjectName("btnPrecActeur")
        self.btnSvActeur = QtWidgets.QPushButton(Acteurs)
        self.btnSvActeur.setGeometry(QtCore.QRect(100, 210, 31, 23))
        self.btnSvActeur.setObjectName("btnSvActeur")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Acteurs)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(17, 10, 351, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbltitreActeur = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbltitreActeur.setObjectName("lbltitreActeur")
        self.horizontalLayout_6.addWidget(self.lbltitreActeur)
        self.TitreduFilm = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.TitreduFilm.setObjectName("TitreduFilm")
        self.horizontalLayout_6.addWidget(self.TitreduFilm)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblnomPersActeur = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lblnomPersActeur.setObjectName("lblnomPersActeur")
        self.horizontalLayout_5.addWidget(self.lblnomPersActeur)
        self.NomPers = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.NomPers.setObjectName("NomPers")
        self.horizontalLayout_5.addWidget(self.NomPers)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbldebutempActeur = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbldebutempActeur.setObjectName("lbldebutempActeur")
        self.horizontalLayout_4.addWidget(self.lbldebutempActeur)
        self.dateDebut = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.dateDebut.setObjectName("dateDebut")
        self.horizontalLayout_4.addWidget(self.dateDebut)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblfinempActeur = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lblfinempActeur.setObjectName("lblfinempActeur")
        self.horizontalLayout_3.addWidget(self.lblfinempActeur)
        self.DateFin = QtWidgets.QDateEdit(self.verticalLayoutWidget_3)
        self.DateFin.setObjectName("DateFin")
        self.horizontalLayout_3.addWidget(self.DateFin)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblcachetActeur = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lblcachetActeur.setObjectName("lblcachetActeur")
        self.horizontalLayout_2.addWidget(self.lblcachetActeur)
        self.cachet = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.cachet.setObjectName("cachet")
        self.horizontalLayout_2.addWidget(self.cachet)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Acteurs)
        QtCore.QMetaObject.connectSlotsByName(Acteurs)

    def retranslateUi(self, Acteurs):
        _translate = QtCore.QCoreApplication.translate
        Acteurs.setWindowTitle(_translate("Acteurs", "Liste des personnages d\'un acteur"))
        self.btnCloseActeur.setText(_translate("Acteurs", "Fermer"))
        self.btnSaveActeur.setText(_translate("Acteurs", "Sauvegarder"))
        self.btnPrecActeur.setText(_translate("Acteurs", "<"))
        self.btnSvActeur.setText(_translate("Acteurs", ">"))
        self.lbltitreActeur.setText(_translate("Acteurs", "Titre du film"))
        self.lblnomPersActeur.setText(_translate("Acteurs", "Nom du personnage"))
        self.lbldebutempActeur.setText(_translate("Acteurs", "Début d\'emploi"))
        self.lblfinempActeur.setText(_translate("Acteurs", "Fin d\'emploi"))
        self.lblcachetActeur.setText(_translate("Acteurs", "Cachet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Acteurs = QtWidgets.QDialog()
    ui = Ui_Acteurs()
    ui.setupUi(Acteurs)
    Acteurs.show()
    sys.exit(app.exec_())
