# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(231, 129)
        self.btnFermer = QtWidgets.QPushButton(Dialog)
        self.btnFermer.setGeometry(QtCore.QRect(140, 100, 75, 23))
        self.btnFermer.setObjectName("btnFermer")
        self.btnFermer.clicked.connect(self._ferme)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 211, 81))
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setObjectName("textEdit")
        self.btnEcrire = QtWidgets.QPushButton(Dialog)
        self.btnEcrire.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.btnEcrire.setObjectName("btnEcrire")
        self.btnFermer.clicked.connect(self._ecrire)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def _ferme(self):
        QtCore.QCoreApplication.quit()
    def _ecrire(self):
        lecture = self.textEdit.get


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mon application"))
        self.btnFermer.setText(_translate("Dialog", "Fermer"))
        self.btnEcrire.setText(_translate("Dialog", "Écriture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
