# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pcadmin\Documents\GitHub\RAC\UI\films.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QDialog

class Ui_Films(object):


    def setupUi(self, Films):
        Films.setObjectName("Films")
        Films.resize(445, 207)
        Films.setSizeGripEnabled(True)
# Bouton de fermeture de la fenêtre
        self.btnClose = QtWidgets.QPushButton(Films)
        self.btnClose.setGeometry(QtCore.QRect(50, 170, 75, 23))
        self.btnClose.setObjectName("btnClose")
        self.btnClose.clicked.connect(self.closeEvent)

        self.btnSuivant = QtWidgets.QPushButton(Films)
        self.btnSuivant.setGeometry(QtCore.QRect(100, 140, 31, 23))
        self.btnSuivant.setObjectName("btnSuivant")
        self.btnPrecedent = QtWidgets.QPushButton(Films)
        self.btnPrecedent.setGeometry(QtCore.QRect(40, 140, 31, 23))
        self.btnPrecedent.setObjectName("btnPrecedent")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Films)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 160, 112))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.btnNouveau = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnNouveau.setObjectName("btnNouveau")
        self.verticalLayout_18.addWidget(self.btnNouveau)
        self.btnSupprimer = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnSupprimer.setObjectName("btnSupprimer")
        self.verticalLayout_18.addWidget(self.btnSupprimer)
        self.btnSauvegarder = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnSauvegarder.setObjectName("btnSauvegarder")
        self.verticalLayout_18.addWidget(self.btnSauvegarder)
        self.btnCharger_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnCharger_2.setObjectName("btnCharger_2")
        self.verticalLayout_18.addWidget(self.btnCharger_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(Films)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 20, 211, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineFilm = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineFilm.setObjectName("lineFilm")
        self.verticalLayout.addWidget(self.lineFilm)
        self.textDescFilm = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textDescFilm.setObjectName("textDescFilm")
        self.verticalLayout.addWidget(self.textDescFilm)

        self.retranslateUi(Films)
        QtCore.QMetaObject.connectSlotsByName(Films)

    def retranslateUi(self, Films):
        _translate = QtCore.QCoreApplication.translate
        Films.setWindowTitle(_translate("Films", "Films"))
        self.btnClose.setText(_translate("Films", "Fermer"))
        self.btnSuivant.setText(_translate("Films", ">"))
        self.btnPrecedent.setText(_translate("Films", "<"))
        self.btnNouveau.setText(_translate("Films", "Nouveau"))
        self.btnSupprimer.setText(_translate("Films", "Supprimer"))
        self.btnSauvegarder.setText(_translate("Films", "Sauvegarder"))
        self.btnCharger_2.setText(_translate("Films", "Charger"))

        # Fenêtre de confirmation de la fermeture de l'application

    def closeEvent(self):
        if e.key() == Qt.Key_Escape:
            self.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Films = QtWidgets.QDialog()
    ui = Ui_Films()
    ui.setupUi(Films)
    Films.show()
    sys.exit(app.exec_())
