# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pcadmin\Documents\GitHub\RAC\UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
Application principale appelant les autres fenêtres, modules et fermant l'application.
"""
from personne import *
from films import *

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QDialog
#   QMessage n'était pas importer depuis QtWidgets et doit être forcer.


from classes import *


class Ui_UImain(object):
    def setupUi(self, UImain):
        UImain.setObjectName("UImain")
        UImain.setWindowModality(QtCore.Qt.WindowModal)
        UImain.resize(252, 134)
        UImain.setAutoFillBackground(False)
        UImain.setSizeGripEnabled(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(UImain)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 211, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

#   Bouton d'accès à la fenêtre Personne
        self.btnPersonne = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnPersonne.setObjectName("btnPersonne")
        self.verticalLayout.addWidget(self.btnPersonne)
        self.btnPersonne.clicked.connect(self.showPersonne)


#   Bouton d'accès à la fenêtre film
        self.btnFilm = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnFilm.setAutoRepeatDelay(310)
        self.btnFilm.setObjectName("btnFilm")
        self.verticalLayout.addWidget(self.btnFilm)
        self.btnFilm.clicked.connect(self.showFilms)

#   Bouton de fermeture principale
        self.btnClose = QtWidgets.QPushButton(UImain)
        self.btnClose.setGeometry(QtCore.QRect(170, 100, 75, 23))
        self.btnClose.setObjectName("btnClose")
        self.btnClose.clicked.connect(self.closeEvent)

        self.retranslateUi(UImain)
        QtCore.QMetaObject.connectSlotsByName(UImain)


    def retranslateUi(self, UImain):
        _translate = QtCore.QCoreApplication.translate
        UImain.setWindowTitle(_translate("UImain", "Menu Principale"))
        self.btnPersonne.setText(_translate("UImain", "Personne"))
        self.btnFilm.setText(_translate("UImain", "Films"))
        self.btnClose.setText(_translate("UImain", "Fermer"))

 # Ouverture de la fenêtre Personne
    def showPersonne(self, checked=None):
        if checked == None: return
        dialog = QDialog()
        dialog.ui = Ui_Personne()
        dialog.ui.setupUi(dialog)
        dialog.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        dialog.exec_()

# Ouverture de la fenêtre Films
    def showFilms(self, checked=None):
        if checked == None: return
        dialog = QDialog()
        dialog.ui = Ui_Films()
        dialog.ui.setupUi(dialog)
        dialog.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        dialog.exec_()

 # Fenêtre de confirmation de la fermeture de l'application
    def closeEvent(self):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Êtes-vous sure de quitter?")
        msgBox.setWindowTitle("Message de fermeture")
        msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        #   Choix du message de fermeture
        res = msgBox.exec_()
        if res == QMessageBox.Ok:
            sys.exit()
        if res == QMessageBox.Cancel:
            return True
        return False

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UImain = QtWidgets.QDialog()
    ui = Ui_UImain()
    ui.setupUi(UImain)
    UImain.show()
    sys.exit(app.exec_())
